name: train_tts_model
data_dir: NISQA_Corpus
output_dir: artifacts
pretrained_model: false
csv_file: NISQA_corpus_file.csv
csv_con: null
csv_deg: filepath_deg
csv_mos_train: mos
csv_mos_val: mos
csv_db_train: [NISQA_TRAIN_SIM, NISQA_TRAIN_LIVE]
csv_db_val: [NISQA_VAL_SIM, NISQA_VAL_LIVE]
tr_epochs: 50
tr_early_stop: 5
tr_bs: 32
tr_bs_val: 32
tr_lr: 0.001
tr_lr_patience: 15
tr_num_workers: 4
tr_parallel: false
tr_ds_to_memory: false
tr_ds_to_memory_workers: 0
tr_device: null
tr_checkpoint: best_only
tr_verbose: 2
tr_bias_mapping: null
tr_bias_min_r: null
tr_bias_anchor_db: null
ms_sr: null
ms_fmax: 20000
ms_n_fft: 4096
ms_hop_length: 0.01
ms_win_length: 0.02
ms_n_mels: 48
ms_seg_length: 15
ms_seg_hop_length: 4
ms_max_segments: 1300
ms_channel: null
model: NISQA
cnn_model: adapt
cnn_c_out_1: 16
cnn_c_out_2: 32
cnn_c_out_3: 64
cnn_kernel_size: !!python/tuple [3, 3]
cnn_dropout: 0.2
cnn_fc_out_h: null
cnn_pool_1: [24, 7]
cnn_pool_2: [12, 5]
cnn_pool_3: [6, 3]
td: self_att
td_sa_d_model: 64
td_sa_nhead: 1
td_sa_pos_enc: false
td_sa_num_layers: 2
td_sa_h: 64
td_sa_dropout: 0.1
td_lstm_h: null
td_lstm_num_layers: null
td_lstm_dropout: null
td_lstm_bidirectional: null
td_2: skip
td_2_sa_d_model: null
td_2_sa_nhead: null
td_2_sa_pos_enc: null
td_2_sa_num_layers: null
td_2_sa_h: null
td_2_sa_dropout: null
td_2_lstm_h: null
td_2_lstm_num_layers: null
td_2_lstm_dropout: null
td_2_lstm_bidirectional: null
pool: att
pool_att_h: 128
pool_att_dropout: 0
yaml: config/train_nisqa_cnn_sa_ap.yaml
mode: main
dim: false
double_ended: false
csv_ref: null
now: 2024-04-11 16:31:40.624015
